/// Flutter icons TheShopIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TheShopIcons
///      fonts:
///       - asset: fonts/TheShopIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TheShopIcons {
  TheShopIcons._();

  static const _kFontFam = 'TheShopIcons';
  static const String? _kFontPkg = null;

  static const IconData catalog_tab_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_tab_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart_tab_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData showcase_tab_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorites_tab_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
